[package]
name = "ferris_eat"
version = "0.1.0"
authors = ["GiyoMoon <giyomoon@gmail.com>"]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "entity", "migration"]

[dependencies.entity]
path = "entity"

[dependencies.migration]
path = "migration"

[dependencies.sea-orm]
version = "0.8.0"
features = ["sqlx-postgres", "runtime-tokio-rustls", "macros", "with-uuid"]

[dependencies.dotenv]
version = "0.15.0"

[dependencies.tokio]
version = "1.18.2"
features = ["macros", "rt-multi-thread", "time"]

[dependencies.axum]
version = "0.5.6"

[dependencies.axum-macros]
version = "0.2.2"

# [dependencies.chrono]
# version = "0.4.19"
# features = ["serde"]

# [dependencies.bcrypt]
# version = "0.13.0"

# [dependencies.cron]
# version = "0.11.0"

# [dependencies.async-recursion]
# version = "1.0.0"
